import argparse
from pathlib import Path

import h5py
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, FFMpegWriter, PillowWriter
import numpy as np


def load_fields(h5_path: Path):
    with h5py.File(h5_path, "r") as f:
        f_values = f["fields/f/value"][:]
        times = f["fields/f/time"][:]
        nx = int(f["parameters/Nx"][()])
        nv = int(f["parameters/Nv"][()])
        x_min = float(f["parameters/xmin"][()])
        x_max = float(f["parameters/xmax"][()])
        v_min = float(f["parameters/vmin"][()])
        v_max = float(f["parameters/vmax"][()])

    return normalize_field_layout(f_values, nx, nv), times, (x_min, x_max, v_min, v_max)


def normalize_field_layout(values: np.ndarray, nx: int, nv: int) -> np.ndarray:
    if values.ndim != 3:
        raise ValueError(f"Expected a 3D field array (time, *, *), got shape {values.shape}.")
    if values.shape[1:] == (nx, nv):
        return values
    if values.shape[1:] == (nv, nx + 1):
        return values[:, :, :-1].transpose(0, 2, 1)
    raise ValueError(
        f"Unsupported field layout {values.shape[1:]} for Nx={nx}, Nv={nv}. "
        "Expected (Nx, Nv) or vmf90-style (Nv, Nx+1)."
    )


def validate_compatibility(
    values_a: np.ndarray,
    times_a: np.ndarray,
    extent_a: tuple[float, float, float, float],
    values_b: np.ndarray,
    times_b: np.ndarray,
    extent_b: tuple[float, float, float, float],
):
    if values_a.shape != values_b.shape:
        raise ValueError(
            f"Input datasets have different shapes: {values_a.shape} vs {values_b.shape}. "
            "Cannot compute a frame-by-frame difference."
        )
    if not np.allclose(times_a, times_b):
        raise ValueError(
            "Input datasets have different time arrays. "
            "Use outputs with the same saved timesteps."
        )
    if not np.allclose(np.asarray(extent_a), np.asarray(extent_b)):
        raise ValueError(
            "Input datasets use different (x, v) domain bounds. "
            "Use outputs defined on the same grid extents."
        )


def create_difference_video(
    h5_file_a: Path,
    h5_file_b: Path,
    output: Path,
    fps: int = 20,
    dpi: int = 120,
    cmap: str = "coolwarm",
):
    values_a, times_a, extent_a = load_fields(h5_file_a)
    values_b, times_b, extent_b = load_fields(h5_file_b)

    validate_compatibility(values_a, times_a, extent_a, values_b, times_b, extent_b)

    difference = values_a - values_b
    absmax = np.max(np.abs(difference))
    vmin, vmax = (-absmax, absmax) if absmax > 0 else (-1e-16, 1e-16)

    fig, ax = plt.subplots(figsize=(7, 4.8))
    im = ax.imshow(
        difference[0].T,
        origin="lower",
        aspect="auto",
        extent=extent_a,
        cmap=cmap,
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
    )
    ax.set_xlabel("x")
    ax.set_ylabel("v")
    title = ax.set_title(f"Difference Δf(x, v), t = {times_a[0]:.4f}")
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label("Δf = f₁ - f₂")

    def update(frame_index: int):
        im.set_data(difference[frame_index].T)
        title.set_text(f"Difference Δf(x, v), t = {times_a[frame_index]:.4f}")
        return im, title

    anim = FuncAnimation(fig, update, frames=difference.shape[0], interval=1000 / fps, blit=False)

    output.parent.mkdir(parents=True, exist_ok=True)
    suffix = output.suffix.lower()
    if suffix == ".gif":
        writer = PillowWriter(fps=fps)
    else:
        writer = FFMpegWriter(fps=fps)

    anim.save(str(output), writer=writer, dpi=dpi)
    plt.close(fig)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=(
            "Create an animation of the distribution difference Δf(x, v, t) = f₁ - f₂ "
            "from two HMF Vlasov HDF5 outputs."
        )
    )
    parser.add_argument("input_a", type=Path, help="Path to first hmf.h5 generated by hmf_vlasov.py")
    parser.add_argument("input_b", type=Path, help="Path to second hmf.h5 generated by hmf_vlasov.py")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("difference.mp4"),
        help="Output video path (.mp4 or .gif)",
    )
    parser.add_argument("--fps", type=int, default=20, help="Frames per second")
    parser.add_argument("--dpi", type=int, default=120, help="Output DPI")
    parser.add_argument("--cmap", default="coolwarm", help="Matplotlib colormap")
    args = parser.parse_args()

    create_difference_video(
        args.input_a,
        args.input_b,
        args.output,
        fps=args.fps,
        dpi=args.dpi,
        cmap=args.cmap,
    )
